=== SingingBush/jour/jour-instrument/src/main/resources/jour.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="aspect">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="typedef" minOccurs="0"/>
				<xs:element ref="pointcut" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="descr" type="xs:string" use="optional" default=""/>
			<xs:attribute name="type" type="xs:string" use="required"/>
			<xs:attribute name="enabled" type="xs:boolean" use="optional" default="true"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="jour">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="aspect" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="debug" type="xs:boolean" use="optional" default="false"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="pointcut">
		<xs:complexType>
			<xs:attribute name="expr" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="typedef" type="xs:string"/>
</xs:schema>

=== SingingBush/jour/jour-instrument/src/test/resources/configTest.jour.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<jour xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="jour.xsd" debug="false">
	<aspect descr="a descr 1" type="tests.jour.instrumentor.ConfigTestInstrumentor" enabled="true">
		<typedef>typedef1</typedef>
		<pointcut expr="* pointcut11()"/>
		<pointcut expr="* pointcut12()"/>
	</aspect>
	<aspect descr="a descr 2" type="tests.jour.instrumentor.ConfigTestInstrumentor" enabled="true">
		<typedef>typedef2</typedef>
		<pointcut expr="* pointcut21()"/>
		<pointcut expr="* pointcut22()"/>
	</aspect>
</jour>

=== SingingBush/jour/jour-examples/process-classes.jour.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<jour xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="jour.xsd" debug="false">

    <aspect descr="MakeEmptyMethod" type="net.sf.jour.instrumentor.MakeEmptyMethodInstrumentor" enabled="true">
        <typedef>net.sf.jour.examples.Extensive*</typedef>
        <pointcut expr="* debug(..)"/>
    </aspect>

    <aspect type="net.sf.jour.instrumentor.ReplaceMethodInstrumentor">
        <typedef>net.sf.jour.examples.Extensive*</typedef>
        <pointcut expr="boolean replace*(..)"/>
        <property name="code" value="return true;"/>
        <property name="oldMethodSufix" value="Original"/>
    </aspect>

    <aspect type="net.sf.jour.instrumentor.ReplaceMethodInstrumentor">
        <typedef>net.sf.jour.examples.Extensive*</typedef>
        <pointcut expr="java.lang.String replace*(..)"/>
        <property name="code">
            <value><![CDATA[
                {
                return "it works!";
                }
            ]]></value>
        </property>
    </aspect>

    <aspect descr="MakeTimedMethod" type="net.sf.jour.instrumentor.MethodExecutionTimeInstrumentor">
        <typedef>net.sf.jour.examples.Extensive*</typedef>
        <pointcut expr="* timed(..)"/>
    </aspect>

    <aspect descr="MakeProtected" type="net.sf.jour.instrumentor.MakeProtectedMethodInstrumentor" enabled="true">
        <typedef>net.sf.jour.examples.MakeProtected</typedef>
        <pointcut expr="* method*(..)"/>
    </aspect>
</jour>
